"""Fail-closed contracts for the source-faithful multi-province route."""

from .household_adapter import (
    ACCEPTED_HA_PUBLIC_API,
    MATLAB_TO_ACCEPTED_HA_FIELD_MAP,
    MATLAB_TO_ACCEPTED_HA_OUTPUT_MAP,
    NO_LEGACY_R5_RUNTIME_DEPENDENCY,
    FrozenHouseholdOutputs,
    MultiProvinceHouseholdInputs,
    StaticHouseholdCall,
    build_static_household_call,
    reject_legacy_runtime_references,
)
from .provenance import DATA_PROVENANCE_MANIFEST, DataArtifactProvenance, YearCacheBinding
from .one_turn import (
    SOURCE_UPDATE_ORDER,
    OneTurnInputs,
    OneTurnResult,
    PreFrozenHouseholdOutputBatch,
    compose_one_turn,
    run_source_faithful_one_turn,
)
from .province_contracts import (
    PROVINCE_ORDER,
    HouseholdOuterOutputs,
    MigrationLaborAllocation,
    ProvinceAxis,
    ProvinceMatrix,
    ProvinceVector,
)
from .steady_state import (
    SOURCE_MAX_ITERATIONS,
    TERMINATION_CONVERGED,
    TERMINATION_MAX_ITERATIONS,
    AdaptiveAction,
    IterationRecord,
    ManualSteadyStateInputs,
    ManualSteadyStateResult,
    SteadyStateConvergenceError,
    run_manual_steady_state,
)

__all__ = [
    "DATA_PROVENANCE_MANIFEST",
    "ACCEPTED_HA_PUBLIC_API",
    "MATLAB_TO_ACCEPTED_HA_FIELD_MAP",
    "MATLAB_TO_ACCEPTED_HA_OUTPUT_MAP",
    "NO_LEGACY_R5_RUNTIME_DEPENDENCY",
    "SOURCE_UPDATE_ORDER",
    "SOURCE_MAX_ITERATIONS",
    "TERMINATION_CONVERGED",
    "TERMINATION_MAX_ITERATIONS",
    "PROVINCE_ORDER",
    "DataArtifactProvenance",
    "AdaptiveAction",
    "FrozenHouseholdOutputs",
    "HouseholdOuterOutputs",
    "MigrationLaborAllocation",
    "IterationRecord",
    "ManualSteadyStateInputs",
    "ManualSteadyStateResult",
    "MultiProvinceHouseholdInputs",
    "OneTurnInputs",
    "OneTurnResult",
    "PreFrozenHouseholdOutputBatch",
    "ProvinceAxis",
    "ProvinceMatrix",
    "ProvinceVector",
    "StaticHouseholdCall",
    "SteadyStateConvergenceError",
    "YearCacheBinding",
    "build_static_household_call",
    "compose_one_turn",
    "reject_legacy_runtime_references",
    "run_source_faithful_one_turn",
    "run_manual_steady_state",
]
